version: "3.9"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 4000:8000

    volumes:
      - .:/app

    environment:
      DBString: mongodb://mongo_db:27017
      JWTSECRET: f88fs8d0a7ddd8hsdva7s-aa

    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
